### ISSUE TITLE
Adicionar um elemento ao código

### ISSUE THREAD

**Issue by canogg** [souzagabriela/calculoCicloMentrual#1]
Adorei o código, super útil para o dia a dia, acho que poderia acrescentar os dias da TPM seguindo a mesma linha de raciocínio e dicas do que poderíamos fazer nesse período para aliviar os sintomas. :)

**Comment by souzagabriela** [comment]
Obrigada Carol, pensei em fazer isso sim depois de melhor a estrutura do código. Acho que seria uma boa acrescentar esses dias e também dizer os sentimentos prováveis durante esse período, né?
